#!/bin/bash
# ICE Quote Agent — one-shot VPS bootstrap.
#
# Run as root on a fresh Ubuntu 22.04+ droplet. The script needs 5 secrets
# which it reads from environment variables (prompts interactively for any
# that are missing):
#
#   ANTHROPIC_API_KEY   — sk-ant-...
#   MS_TENANT_ID        — Azure AD tenant GUID
#   MS_CLIENT_ID        — Azure AD app (client) GUID
#   MS_CLIENT_SECRET    — Azure AD client secret value
#   AGENT_MAILBOX       — mailbox to poll (e.g. quotes@ice-contractors.com)
#   REVIEWER_EMAIL      — draft recipient (e.g. info@ice-contractors.com)
#
# One-liner (fill in secrets inline):
#
#   export ANTHROPIC_API_KEY='sk-ant-...' \
#          MS_TENANT_ID='...' \
#          MS_CLIENT_ID='...' \
#          MS_CLIENT_SECRET='...' \
#          AGENT_MAILBOX='quotes@ice-contractors.com' \
#          REVIEWER_EMAIL='info@ice-contractors.com'
#   curl -fsSL https://raw.githubusercontent.com/TheMFree/ice-quote-agent/main/deploy/bootstrap.sh | bash
#
# When it finishes successfully, the agent will be running under systemd
# as `ice-quote-agent.service` and polling the mailbox once a minute.

set -euo pipefail

REPO_URL="https://github.com/TheMFree/ice-quote-agent.git"
INSTALL_DIR="/opt/ice-quote-agent"
AGENT_USER="iceagent"
LOG_DIR="/var/log/ice-quote-agent"

# ---------- pre-flight ----------
if [[ "${EUID}" -ne 0 ]]; then
  echo "This script must run as root (try: sudo bash $0)" >&2
  exit 1
fi

prompt_secret() {
  local varname="$1" label="$2" hidden="${3:-1}"
  if [[ -z "${!varname:-}" ]]; then
    echo
    echo "Enter ${label}:"
    if [[ "${hidden}" == "1" ]]; then
      read -rs value
    else
      read -r value
    fi
    echo
    printf -v "${varname}" '%s' "${value}"
  fi
  if [[ -z "${!varname}" ]]; then
    echo "${varname} is required — aborting." >&2
    exit 1
  fi
}

prompt_secret ANTHROPIC_API_KEY "Anthropic API key (sk-ant-...)"        1
prompt_secret MS_TENANT_ID      "Microsoft tenant id (GUID)"             0
prompt_secret MS_CLIENT_ID      "Microsoft app (client) id (GUID)"       0
prompt_secret MS_CLIENT_SECRET  "Microsoft client secret value"          1
prompt_secret AGENT_MAILBOX     "Agent mailbox (quotes@ice-contractors.com)" 0
prompt_secret REVIEWER_EMAIL    "Reviewer email (info@ice-contractors.com)" 0

echo "==> Installing OS packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y --no-install-recommends \
  git \
  python3 \
  python3-venv \
  python3-pip \
  poppler-utils \
  libreoffice-core \
  libreoffice-writer \
  ca-certificates

echo "==> Creating service user (${AGENT_USER})..."
if ! id "${AGENT_USER}" >/dev/null 2>&1; then
  adduser --system --group --home "${INSTALL_DIR}" --shell /usr/sbin/nologin "${AGENT_USER}"
fi

echo "==> Cloning / updating repo..."
if [[ -d "${INSTALL_DIR}/.git" ]]; then
  git -C "${INSTALL_DIR}" fetch --all
  git -C "${INSTALL_DIR}" reset --hard origin/main
else
  rm -rf "${INSTALL_DIR}.tmp"
  git clone --depth 1 "${REPO_URL}" "${INSTALL_DIR}.tmp"
  mkdir -p "${INSTALL_DIR}"
  shopt -s dotglob
  cp -R "${INSTALL_DIR}.tmp"/* "${INSTALL_DIR}/"
  shopt -u dotglob
  rm -rf "${INSTALL_DIR}.tmp"
fi

echo "==> Creating python venv..."
python3 -m venv "${INSTALL_DIR}/.venv"
"${INSTALL_DIR}/.venv/bin/pip" install --upgrade pip wheel
"${INSTALL_DIR}/.venv/bin/pip" install -r "${INSTALL_DIR}/requirements.txt"

echo "==> Decoding proposal template from committed base64 parts..."
TEMPLATE_DIR="${INSTALL_DIR}/templates"
TEMPLATE_DOCX="${TEMPLATE_DIR}/ICE_Contractors_Proposal_Template.docx"
PARTS=( "${TEMPLATE_DIR}"/ICE_Contractors_Proposal_Template.docx.b64.part_* )
if (( ${#PARTS[@]} > 0 )) && [[ -f "${PARTS[0]}" ]]; then
  # Sort ensures part_00, part_01, ... are concatenated in the right order.
  cat $(printf '%s\n' "${PARTS[@]}" | sort) | base64 -d > "${TEMPLATE_DOCX}"
  echo "    wrote ${TEMPLATE_DOCX} ($(stat -c%s "${TEMPLATE_DOCX}") bytes)"
else
  echo "    WARNING: no template parts found — falling back to legacy build_template.py"
  cd "${INSTALL_DIR}"
  "${INSTALL_DIR}/.venv/bin/python" "${INSTALL_DIR}/build_template.py" || true
  cd /
fi

echo "==> Writing ${INSTALL_DIR}/.env ..."
umask 077
cat > "${INSTALL_DIR}/.env" <<ENVEOF
# Auto-generated by bootstrap.sh — keep this file chmod 600.

ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

MS_TENANT_ID=${MS_TENANT_ID}
MS_CLIENT_ID=${MS_CLIENT_ID}
MS_CLIENT_SECRET=${MS_CLIENT_SECRET}

AGENT_MAILBOX=${AGENT_MAILBOX}
REVIEWER_EMAIL=${REVIEWER_EMAIL}

# Set to true to test extraction without sending the reviewer draft.
DRY_RUN=false

POLL_INTERVAL_SECONDS=60
LOG_DIR=${LOG_DIR}
OUTPUT_DIR=${INSTALL_DIR}/output
ENVEOF
umask 022
chmod 600 "${INSTALL_DIR}/.env"

echo "==> Creating runtime dirs..."
mkdir -p "${LOG_DIR}" "${INSTALL_DIR}/output" "${INSTALL_DIR}/logs"

echo "==> Chowning to ${AGENT_USER}..."
chown -R "${AGENT_USER}:${AGENT_USER}" "${INSTALL_DIR}" "${LOG_DIR}"

echo "==> Installing systemd service..."
install -m 644 "${INSTALL_DIR}/systemd/ice-quote-agent.service" \
  /etc/systemd/system/ice-quote-agent.service
systemctl daemon-reload
systemctl enable ice-quote-agent.service
systemctl restart ice-quote-agent.service

sleep 2
echo
echo "==> Service status:"
systemctl --no-pager --full status ice-quote-agent.service || true
echo
echo "==> Recent journal output:"
journalctl -u ice-quote-agent.service -n 30 --no-pager || true
echo
echo "Bootstrap complete. Tail live output with:"
echo "  journalctl -u ice-quote-agent.service -f"
